const cities = [
  "Abu Dhabi",
  "Abu Dhabi Town",
  "Accra",
  "Accra Town",
  "Adelaide",
  "Adelaide Town",
  "Agra",
  "Agra Town",
  "Ahmedabad",
  "Ahmedabad Town",
  "Ajmer",
  "Ajmer Town",
  "Albuquerque",
  "Albuquerque Town",
  "Aleppo",
  "Aleppo Town",
  "Alexandria",
  "Alexandria Town",
  "Allahabad",
  "Allahabad Town",
  "Amman",
  "Amman Town",
  "Amsterdam",
  "Amsterdam Town",
  "Anchorage",
  "Anchorage Town",
  "Ankara",
  "Ankara Town",
  "Antwerp",
  "Antwerp Town",
  "Asuncion",
  "Asuncion Town",
  "Athens",
  "Athens Town",
  "Atlanta",
  "Atlanta Town",
  "Auckland",
  "Auckland Town",
  "Aurangabad",
  "Aurangabad Town",
  "Austin",
  "Austin Town",
  "Baghdad",
  "Baghdad Town",
  "Baku",
  "Baku Town",
  "Bali",
  "Bali Town",
  "Baltimore",
  "Baltimore Town",
  "Bamako",
  "Bamako Town",
  "Bandung",
  "Bandung Town",
  "Bangalore",
  "Bangalore Town",
  "Bangkok",
  "Bangkok Town",
  "Bangui",
  "Bangui Town",
  "Barcelona",
  "Barcelona Town",
  "Bareilly",
  "Bareilly Town",
  "Barnaul",
  "Barnaul Town",
  "Barranquilla",
  "Barranquilla Town",
  "Basel",
  "Basel Town",
  "Beijing",
  "Beijing Town",
  "Beirut",
  "Beirut Town",
  "Belfast",
  "Belfast Town",
  "Belgrade",
  "Belgrade Town",
  "Belmopan",
  "Belmopan Town",
  "Benghazi",
  "Benghazi Town",
  "Bergen",
  "Bergen Town",
  "Berlin",
  "Berlin Town",
  "Bern",
  "Bern Town",
  "Bhopal",
  "Bhopal Town",
  "Bhubaneswar",
  "Bhubaneswar Town",
  "Bikaner",
  "Bikaner Town",
  "Bilbao",
  "Bilbao Town",
  "Birmingham",
  "Birmingham Town",
  "Bissau",
  "Bissau Town",
  "Bogotá",
  "Bogotá Town",
  "Boston",
  "Boston Town",
  "Brasília",
  "Brasília Town",
  "Bratislava",
  "Bratislava Town",
  "Brazzaville",
  "Brazzaville Town",
  "Brisbane",
  "Brisbane Town",
  "Bristol",
  "Bristol Town",
  "Brno",
  "Brno Town",
  "Brussels",
  "Brussels Town",
  "Bucharest",
  "Bucharest Town",
  "Budapest",
  "Budapest Town",
  "Buenos Aires",
  "Buenos Aires Town",
  "Bujumbura",
  "Bujumbura Town",
  "Bursa",
  "Bursa Town",
  "Busan",
  "Busan Town",
  "Cairo",
  "Cairo Town",
  "Calgary",
  "Calgary Town",
  "Cali",
  "Cali Town",
  "Canberra",
  "Canberra Town",
  "Cape Town",
  "Cape Town Town",
  "Caracas",
  "Caracas Town",
  "Cardiff",
  "Cardiff Town",
  "Casablanca",
  "Casablanca Town",
  "Cebu",
  "Cebu Town",
  "Chandigarh",
  "Chandigarh Town",
  "Chennai",
  "Chennai Town",
  "Chicago",
  "Chicago Town",
  "Chisinau",
  "Chisinau Town",
  "Cincinnati",
  "Cincinnati Town",
  "Cleveland",
  "Cleveland Town",
  "Colombo",
  "Colombo Town",
  "Columbus",
  "Columbus Town",
  "Conakry",
  "Conakry Town",
  "Copenhagen",
  "Copenhagen Town",
  "Cork",
  "Cork Town",
  "Curitiba",
  "Curitiba Town",
  "Córdoba",
  "Córdoba Town",
  "Daegu",
  "Daegu Town",
  "Daejeon",
  "Daejeon Town",
  "Dakar",
  "Dakar Town",
  "Dallas",
  "Dallas Town",
  "Damascus",
  "Damascus Town",
  "Dammam",
  "Dammam Town",
  "Dar es Salaam",
  "Dar es Salaam Town",
  "Darjeeling",
  "Darjeeling Town",
  "Davao",
  "Davao Town",
  "Dehradun",
  "Dehradun Town",
  "Delhi",
  "Delhi Town",
  "Denver",
  "Denver Town",
  "Detroit",
  "Detroit Town",
  "Dhaka",
  "Dhaka Town",
  "Doha",
  "Doha Town",
  "Donetsk",
  "Donetsk Town",
  "Douala",
  "Douala Town",
  "Dresden",
  "Dresden Town",
  "Dubai",
  "Dubai Town",
  "Dublin",
  "Dublin Town",
  "Durban",
  "Durban Town",
  "Edinburgh",
  "Edinburgh Town",
  "Edmonton",
  "Edmonton Town",
  "Enugu",
  "Enugu Town",
  "Erbil",
  "Erbil Town",
  "Eskisehir",
  "Eskisehir Town",
  "Faridabad",
  "Faridabad Town",
  "Fes",
  "Fes Town",
  "Florence",
  "Florence Town",
  "Fortaleza",
  "Fortaleza Town",
  "Frankfurt",
  "Frankfurt Town",
  "Freetown",
  "Freetown Town",
  "Fukuoka",
  "Fukuoka Town",
  "Gaborone",
  "Gaborone Town",
  "Gangtok",
  "Gangtok Town",
  "Gaza",
  "Gaza Town",
  "Geneva",
  "Geneva Town",
  "Genoa",
  "Genoa Town",
  "Giza",
  "Giza Town",
  "Glasgow",
  "Glasgow Town",
  "Goa",
  "Goa Town",
  "Gothenburg",
  "Gothenburg Town",
  "Graz",
  "Graz Town",
  "Guadalajara",
  "Guadalajara Town",
  "Guangzhou",
  "Guangzhou Town",
  "Guatemala City",
  "Guatemala City Town",
  "Guntur",
  "Guntur Town",
  "Guwahati",
  "Guwahati Town",
  "Gwalior",
  "Gwalior Town",
  "Hamburg",
  "Hamburg Town",
  "Hangzhou",
  "Hangzhou Town",
  "Hanoi",
  "Hanoi Town",
  "Harare",
  "Harare Town",
  "Havana",
  "Havana Town",
  "Helsinki",
  "Helsinki Town",
  "Hiroshima",
  "Hiroshima Town",
  "Ho Chi Minh City",
  "Ho Chi Minh City Town",
  "Hong Kong",
  "Hong Kong Town",
  "Honolulu",
  "Honolulu Town",
  "Houston",
  "Houston Town",
  "Hyderabad",
  "Hyderabad Town",
  "Ibadan",
  "Ibadan Town",
  "Istanbul",
  "Istanbul Town",
  "Izmir",
  "Izmir Town",
  "Jaipur",
  "Jaipur Town",
  "Jakarta",
  "Jakarta Town",
  "Jalandhar",
  "Jalandhar Town",
  "Jammu",
  "Jammu Town",
  "Jamshedpur",
  "Jamshedpur Town",
  "Jerusalem",
  "Jerusalem Town",
  "Johannesburg",
  "Johannesburg Town",
  "Kabul",
  "Kabul Town",
  "Kampala",
  "Kampala Town",
  "Kanpur",
  "Kanpur Town",
  "Kansas City",
  "Kansas City Town",
  "Karachi",
  "Karachi Town",
  "Kathmandu",
  "Kathmandu Town",
  "Kiev",
  "Kiev Town",
  "Kigali",
  "Kigali Town",
  "Kobe",
  "Kobe Town",
  "Kochi",
  "Kochi Town",
  "Kolkata",
  "Kolkata Town",
  "Kota",
  "Kota Town",
  "Krakow",
  "Krakow Town",
  "Kuala Lumpur",
  "Kuala Lumpur Town",
  "Kumasi",
  "Kumasi Town",
  "Kunming",
  "Kunming Town",
  "Kuwait City",
  "Kuwait City Town",
  "Kyoto",
  "Kyoto Town",
  "Lagos",
  "Lagos Town",
  "Lahore",
  "Lahore Town",
  "Las Vegas",
  "Las Vegas Town",
  "Leeds",
  "Leeds Town",
  "Leipzig",
  "Leipzig Town",
  "Lille",
  "Lille Town",
  "Lima",
  "Lima Town",
  "Lisbon",
  "Lisbon Town",
  "Liverpool",
  "Liverpool Town",
  "Ljubljana",
  "Ljubljana Town",
  "London",
  "London Town",
  "Los Angeles",
  "Los Angeles Town",
  "Lucknow",
  "Lucknow Town",
  "Ludhiana",
  "Ludhiana Town",
  "Luxor",
  "Luxor Town",
  "Lyon",
  "Lyon Town",
  "Macau",
  "Macau Town",
  "Madrid",
  "Madrid Town",
  "Madurai",
  "Madurai Town",
  "Makati",
  "Makati Town",
  "Malaga",
  "Malaga Town",
  "Male",
  "Male Town",
  "Managua",
  "Managua Town",
  "Manchester",
  "Manchester Town",
  "Manila",
  "Maputo",
  "Marseille",
  "Mashhad",
  "Matsuyama",
  "Medan",
  "Medellín",
  "Melbourne",
  "Memphis",
  "Mexico City",
  "Miami",
  "Milan",
  "Milwaukee",
  "Minneapolis",
  "Minsk",
  "Mombasa",
  "Monaco",
  "Monrovia",
  "Monterrey",
  "Montevideo",
  "Montreal",
  "Moscow",
  "Mumbai",
  "Munich",
  "Muscat",
  "Mysore",
  "Nagoya",
  "Nagpur",
  "Nairobi",
  "Nanjing",
  "Naples",
  "Nashville",
  "Nassau",
  "New Delhi",
  "New Orleans",
  "New York",
  "Newcastle",
  "Nice",
  "Ningbo",
  "Nizhny Novgorod",
  "Noida",
  "Norwich",
  "Nuremberg",
  "Odessa",
  "Okinawa",
  "Omaha",
  "Osaka",
  "Oslo",
  "Ottawa",
  "Palembang",
  "Palermo",
  "Panama City",
  "Panjim",
  "Paris",
  "Patna",
  "Pattaya",
  "Pekanbaru",
  "Perth",
  "Philadelphia",
  "Phnom Penh",
  "Phoenix",
  "Pisa",
  "Plymouth",
  "Podgorica",
  "Port Louis",
  "Port Moresby",
  "Port-au-Prince",
  "Porto",
  "Porto Alegre",
  "Portsmouth",
  "Prague",
  "Pretoria",
  "Pune",
  "Puri",
  "Pusan",
  "Quito",
  "Raipur",
  "Rajkot",
  "Ranchi",
  "Rangoon",
  "Ras Al Khaimah",
  "Rawalpindi",
  "Recife",
  "Reykjavik",
  "Riga",
  "Rio de Janeiro",
  "Riyadh",
  "Rome",
  "Rotterdam",
  "Sacramento",
  "Saint Petersburg",
  "Salalah",
  "Salem",
  "Salvador",
  "San Diego",
  "San Francisco",
  "San Jose",
  "San Juan",
  "San Salvador",
  "Sanaa",
  "Santiago",
  "Santo Domingo",
  "Sapporo",
  "Sarajevo",
  "Saskatoon",
  "Seattle",
  "Seoul",
  "Seville",
  "Shanghai",
  "Sharjah",
  "Shenzhen",
  "Shillong",
  "Shimla",
  "Singapore",
  "Skopje",
  "Sofia",
  "Split",
  "Stockholm",
  "Stuttgart",
  "Surabaya",
  "Surat",
  "Suva",
  "Sydney",
  "Tabriz",
  "Taipei",
  "Tallinn",
  "Tangier",
  "Tashkent",
  "Tbilisi",
  "Tegucigalpa",
  "Tehran",
  "Tel Aviv",
  "Thane",
  "Thimphu",
  "Thiruvananthapuram",
  "Tianjin",
  "Tijuana",
  "Tirupati",
  "Tokyo",
  "Toronto",
  "Toulouse",
  "Tripoli",
  "Trivandrum",
  "Tunis",
  "Udaipur",
  "Ulaanbaatar",
  "Vadodara",
  "Valencia",
  "Vancouver",
  "Varanasi",
  "Venice",
  "Verona",
  "Victoria",
  "Vienna",
  "Vijayawada",
  "Vilnius",
  "Visakhapatnam",
  "Vladivostok",
  "Warsaw",
  "Washington D.C.",
  "Wellington",
  "Windhoek",
  "Winnipeg",
  "Wrocław",
  "Xi’an",
  "Yangon",
  "Yerevan",
  "Yokohama",
  "Zagreb",
  "Zanzibar",
  "Zurich"
];